### ISSUE TITLE
Not all Configurations are submitted via custom values.yaml

### ISSUE THREAD

**Issue by InfinityShare** [traccar/traccar-helm#27]
Problem: Specifying a custom yaml, database options are not provided as configuration

If you want to change the Database to MS-SQL eg. the configuration is not taken, instead its using the default mysql and provides them in the config map on Kubernetes.

e.g. custom values:

```
image:
  flavor: "ubuntu"
database:
  driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  url: "jdbc:sqlserver://123.123.123.123;databaseName=TraccarDV;user= DbAccountName;password=#SomeSuperStrongPasswordHere1234;trustServerCertificate=true;"
  user: "DbAccountName"
  password: "SomeSuperStrongPasswordHere1234"
```
